on:
  schedule:
    - cron: "*/5 * * * *"
name: Stale Bot workflow
jobs:
  build:
    name: stale
    runs-on: ubuntu-latest
    steps:
      - name: stale
        id: stale
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 20
          days-before-close: 10
          operations-per-run: 5000
          stale-issue-message: |
            Hey there!
            This issue has gone quiet. Spooky quiet. 👻
            We get a lot of issues, so we currently close issues after 30 days of inactivity. It’s been at least 20 days since the last update here.
            If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not stale" to keep this issue open!
            As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) for more information about opening PRs, triaging issues, and contributing!
            Thanks for being a part of the Gatsby community! 💪💜
          exempt-issue-labels: |
            not stale
